%YAML:1.0

cam0:
  T_cam_imu:
    - [0.9998575425571182, 0.0004748315430845883, 0.01687214054721262, 0.010702447297320459]
    - [-0.00021596411881264285, 0.9998822904379329, -0.015341402416057751, 0.009730029322014616]
    - [-0.01687743911671998, 0.015335573142133588, 0.9997399523102307, 0.0021034451951676427]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: []
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [913.3385620117188, 912.2628784179688, 650.9879150390625, 342.4716796875]
  resolution: [1280, 720]
  rostopic: /image
  timeshift_cam_imu: 0.00464416332034062
