# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: position_controllers/GripperActionController


    base_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    joint: gripper_virtual_joint
base_controller:
  ros__parameters:
    joints:
      - virtual_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
arm_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity