# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
    - base_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - virtual_joint
      - link1_joint
      - link2_joint
      - link3_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - gripper_virtual_joint
    action_ns: gripper_cmd
    default: true
  base_controller:
    type: FollowJointTrajectory
    joints:
      - virtual_joint