controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_controller:
      type: mecanum_drive_controller/MecanumDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController  

base_controller:
  ros__parameters:
    
    reference_timeout: 1.0
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    
    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.0185
      sum_of_robot_center_projection_on_X_Y_axis: 0.227

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: false
    twist_covariance_diagonal: [0.01, 0.01, 0.0, 0.0, 0.0, 0.005]
    pose_covariance_diagonal:  [0.01,  0.01,  0.0, 0.0, 0.0, 0.02]

arm_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
      
gripper_controller:
  ros__parameters:
    joint: gripper_virtual_joint
    allow_stalling: true